### ISSUE TITLE
Perception evaluation with sample_dataset

### ISSUE THREAD

**Issue by muensterjan** [tier4/driving_log_replayer#221]
Hello everybody,

I followed the installation guide to set up the perception evaluation and used the sample_dataset to check the evaluation, as described in Quick Start/ Perception Evaluation.

The results of the simulation are always like this:

$ driving_log_replayer simulation run -p perception --rate 0.5
.
.
.
test case 1 / 1 : use case: sample_dataset
-------------- ---------- ---------------- ----------
TestResult: Failed
Failed: 6 / 19 -> 31.58%

The number of executed tests varies between "NoData" and ~ 50. But the result is "Failed" every time. It seems like the point cloud only refreshes sporadically in rviz2.
The /sensing/lidar/concatenated/pointcloud Topic has an average rate of 0.3-0.4 Hz while testing.

The workload of the used PC is not a problem.
Am I doing something wrong?

Thank you!

**Comment by FranzAlbers** [comment]
Hello,

thanks for developing these really awesome autoware tools! We wanted to evaluate the Autoware algorithms on data from our research vehicle and experienced similar results as @muensterjan.

I followed the instructions for [installing](https://tier4.github.io/driving_log_replayer/quick_start/installation/), [setting up the resources](https://tier4.github.io/driving_log_replayer/quick_start/setup/), and [evaluating the perception with the sample dataset](https://tier4.github.io/driving_log_replayer/quick_start/perception/).

During testing, I observed stable 5 hz for the point cloud topic. The computational workload shouldn't be an issue, as the GPU and CPU utilization stayed constantly below 50% workload while running the driving log evaluator for the perception evaluation.
As far as I can say, the output in rviz2 looked fine. Vehicles were detected and trajectories for two dynamic vehicles were predicted. 

However, the tests currently fail and we see various input data timeout errors from the system error monitor. Is this at the moment expected or is this an issue?
I've attached the output of the driving log replayer launch file:
[driving_log_replayer_output.txt](https://github.com/tier4/driving_log_replayer/files/12600309/driving_log_replayer_output.txt)

I used the Autoware release/v1.0_beta branch for testing this.
Any help would be highly appreciated.
