### ISSUE TITLE
perception.criteria return "FAIL" when the ground truth is none

### ISSUE THREAD

**Issue by miursh** [tier4/driving_log_replayer#304]
### Description
In the current implementation, if the ground truth is zero and the number of recognized results is also zero, it is judged as a failure.
https://github.com/tier4/driving_log_replayer/blob/develop/driving_log_replayer/driving_log_replayer/criteria/perception.py#L178-L179

### Expected behavior
When the ground truth is zero, return SUCCESS if the number of recognized results is also zero.

**Comment by YoshiRi** [comment]
I got it.

So the current logic is like following chart:

| GT \  Tracking | exist      | no exsit        |
|----------------|------------|-----------------|
| exist          | calc score | fail(TN)        |
| no exist       | fail(FP)   | fail(currently) |

and it should be like following:

I think current logic is like following chart
| GT \  Tracking | exist      | no exsit        |
|----------------|------------|-----------------|
| exist          | calc score | fail(TN)        |
| no exist       | fail(FP)   | success |
