### ISSUE TITLE
NDT Localization Evaluation sample result in failed

### ISSUE THREAD

**Issue by a-maumau** [tier4/driving_log_replayer#542]
The test scenario sample in [NDT Localization Evaluation](https://tier4.github.io/driving_log_replayer/quick_start/localization/) will result in `TestResult: Failed`.

```
> dlr simulation run -p localization  -l play_rate:=0.5
...
TestResult: Failed
Failed: Convergence (Fail): 588 / 670 -> 87.76%, Reliability (Fail): NVTL Sequential NG Count: 10 (Total Test: 670, Average: 2.43173, StdDev: 0.15770), NDT Availability (Success): NDT available
```

Is this intended or my environment issue?

**Comment by hayato-m126** [comment]
If the bag slice process is followed as in [this tutorial](https://tier4.github.io/driving_log_replayer/quick_start/localization/), the length of the bag will be 1649138880 to 1649138910 for 30 seconds.
Since 10Hz, the maximum is 300topic, so 588 / 670 is obviously wrong.
